name: JR IT Consultancy
title: Thoughts on cloud migration and end-user computing architecture
description: I write about IT things that are interesting to me, and that I will surely forget next week
markdown: kramdown
theme: jekyll-theme-cayman